name: Practice Workflow

on:
  push:
    branches: master

  workflow_dispatch:
    branches: master

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: npm lint
      - name: Test code
        run: npm test
      - name: Build code
        run: npm build
      - name: deploy
        run: echo "deploy..."
